---
apiVersion: v1
kind: flag-configuration

flag: lkBoolean

enabled: false

defaultValue: true

conditions:
  - allOf:
      - property:
          name: rox.app_release
          operator: semver-eq
          operands:
              - "2"
    flagValue:
      valueWrittenInCode: true
